describe("Test various characters in TicTacToeGame", () => {
    it("User visits Tic Tac Toe Game and tests various inputs of characters", () => {
      cy.visit("https://jsfiddle.net/sbajus/be054c26/")
      let gameSize = 3
      cy.frameLoaded()
      cy.iframe().find('[id="number"]').should("be.visible").type('abcdefg').click()
      cy.iframe().find('[id="start"]').should("be.visible").click()
      cy.iframe().find('[id="table"]').should("not.be.visible")
      cy.iframe().find('[id="number"]').clear()
      cy.iframe().find('[id="number"]').should("be.visible").type('~!@#$%^&*()_+')
      cy.iframe().find('[id="start"]').should("be.visible").click()
      cy.iframe().find('[id="table"]').should("not.be.visible")
      cy.iframe().find('[id="number"]').clear()
      cy.iframe().find('[id="number"]').should("be.visible").type('abcdefg~!@#$%^&*()_+')
      cy.iframe().find('[id="start"]').should("be.visible").click()
      cy.iframe().find('[id="table"]').should("not.be.visible")
      cy.iframe().find('[id="number"]').clear()
      cy.iframe().find('[id="number"]').should("be.visible").type('1234567890abcdefg~!@#$%^&*()_+')
      cy.iframe().find('[id="start"]').should("be.visible").click()
      cy.iframe().find('[id="table"]').should("not.be.visible")
      cy.iframe().find('[id="number"]').clear()
      cy.iframe().find('[id="number"]').should("be.visible").type(gameSize)
      cy.iframe().find('[id="start"]').should("be.visible").click()
      cy.iframe().find('[id="table"]').should("be.visible")
      cy.iframe()
        .find("table td")
        .should("have.lengthOf", gameSize*gameSize)
    })
  })